# Generated by Django 2.0 on 2018-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='名字')),
                ('content', models.CharField(blank=True, max_length=64, null=True, verbose_name='内容')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名字')),
                ('value', models.CharField(blank=True, max_length=64, null=True, verbose_name='值')),
            ],
        ),
    ]
