# Generated by Django 2.0 on 2018-09-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='题卡')),
                ('example', models.CharField(blank=True, max_length=64, null=True, verbose_name='样例')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='顺序')),
            ],
        ),
    ]
