# Generated by Django 2.0 on 2018-09-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='题卡')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='顺序')),
            ],
        ),
        migrations.AlterField(
            model_name='exercisebook',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='练习簿'),
        ),
        migrations.AddField(
            model_name='exercisecard',
            name='exercise_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.ExerciseBook'),
        ),
    ]
