# Generated by Django 2.0 on 2018-09-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20180905_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名字')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='顺序')),
                ('exercise_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.ExerciseCard')),
            ],
        ),
    ]
