# Generated by Django 2.0 on 2018-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='答案'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='question',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='问题'),
        ),
    ]
