# Generated by Django 2.0 on 2018-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20180914_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='描述'),
        ),
    ]
