# Generated by Django 2.0 on 2018-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20180914_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
