# Generated by Django 2.0 on 2018-09-14 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0008_record_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('total_time', models.IntegerField(blank=True, default=1000, null=True, verbose_name='总计时间')),
            ],
        ),
        migrations.AlterField(
            model_name='exercisebook',
            name='description',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='exercisebook',
            name='example',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='样例'),
        ),
        migrations.AlterField(
            model_name='exercisecard',
            name='description',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='exercisebookrecord',
            name='exercise_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.ExerciseCard'),
        ),
        migrations.AddField(
            model_name='exercisebookrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
