# Generated by Django 2.0 on 2018-09-14 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0009_auto_20180914_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseBookRecord',
            new_name='ExerciseCardRecord',
        ),
        migrations.AddField(
            model_name='record',
            name='exercise_card_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.ExerciseCardRecord'),
        ),
    ]
