# Generated by Django 2.0 on 2018-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20180915_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecardrecord',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总计时间'),
        ),
    ]
