# Generated by Django 2.0 on 2018-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20180915_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecardrecord',
            name='right_ratio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='正确率'),
        ),
    ]
