# Generated by Django 2.0 on 2018-09-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(blank=True, max_length=128, verbose_name='头像')),
                ('nickName', models.CharField(blank=True, max_length=128, verbose_name='昵称')),
                ('avatarUrl', models.CharField(blank=True, max_length=128, verbose_name='头像')),
                ('gender', models.CharField(blank=True, max_length=128, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=128, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='城市')),
                ('language', models.CharField(blank=True, max_length=128, verbose_name='语言')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('timestamp', models.IntegerField(verbose_name='时间戳')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('session_key', models.CharField(blank=True, max_length=128, verbose_name='session_key')),
            ],
        ),
    ]
