# Generated by Django 2.0 on 2018-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='city',
            field=models.CharField(blank=True, max_length=24, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='country',
            field=models.CharField(blank=True, max_length=24, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='language',
            field=models.CharField(blank=True, max_length=10, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='openId',
            field=models.CharField(blank=True, max_length=128, verbose_name='openId'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='province',
            field=models.CharField(blank=True, max_length=24, verbose_name='省份'),
        ),
    ]
