# Generated by Django 2.0 on 2018-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20180914_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='gender',
            field=models.IntegerField(blank=True, verbose_name='性别'),
        ),
    ]
